### ISSUE TITLE
具体的模型技术是什么呢？

### ISSUE THREAD

**Issue by yangyang1-0** [wongself/nobody-loves-problem#2]
你好，榨菜哥，按照您的引导，目前query_extract接口已经在本地成功运行了，另外就是想问下该项目的具体原理与用到的模型技术是什么呢？ps：请原谅前面对您的称呼，目前我们组成员全部称您为榨菜哥。

**Comment by wongself** [comment]
命名实体识别模块使用的是[基于片段的模型](https://github.com/lavis-nlp/spert)，而网站基于 django 搭建。

**Comment by yangyang1-0** [comment]
你好，榨菜：
&nbsp; &nbsp; &nbsp; &nbsp;在使用您的项目的时候，经常会产生一个错误，类似：RuntimeError: The expanded size of the tensor (1120) must match the existing size (512) at non-singleton dimension 1.&nbsp; Target sizes: [1, 1120].&nbsp; Tensor sizes: [1, 512]，想请问下如上的类似错误该如何解决呢？
&nbsp; &nbsp; &nbsp; &nbsp;希望收到您的回复，谢谢.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wongself/nobody-loves-problem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 下午3:58
***@***.***&gt;;
抄送:&nbsp;"S * Colourful  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [wongself/nobody-loves-problem] 具体的模型技术是什么呢？ (Issue #2)





 
命名实体识别模块使用的是基于片段的模型，而网站基于 django 搭建。

**Comment by wongself** [comment]
可能是因为输入过长，您需要截短过长的句子。
PS: 请善用搜索引擎。
